version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - ./dbdata/data:/var/lib/mysql
      - ./dbdata/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./dbdata/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:33306