CREATE TABLE IF NOT EXISTS articles(
  id serial PRIMARY KEY,
  title VARCHAR (50) NOT NULL,
  content VARCHAR (50) NOT NULL,
  author_id BIGINT UNSIGNED NOT NULL,
  INDEX (author_id),
  FOREIGN KEY (author_id)
  REFERENCES users(id)
  ON UPDATE CASCADE ON DELETE RESTRICT
);